// data.ts

import { UserStatus } from "@/types";

export const statusColors: Record<UserStatus, string> = {
  active: "bg-green-500",
  inactive: "bg-gray-400",
  blocked: "bg-red-500",
  unblocked: "bg-blue-500",
};

export const currencies = [
  { value: "AED", name: "United Arab Emirates dirham" },
  { value: "AFN", name: "Afghan afghani" },
  { value: "ALL", name: "Albanian lek" },
  { value: "AMD", name: "Armenian dram" },
  { value: "ANG", name: "Netherlands Antillean guilder" },
  { value: "AOA", name: "Angolan kwanza" },
  { value: "ARS", name: "Argentine peso" },
  { value: "AUD", name: "Australian dollar" },
  { value: "AWG", name: "Aruban florin" },
  { value: "AZN", name: "Azerbaijani manat" },
  { value: "BAM", name: "Bosnia and Herzegovina convertible mark" },
  { value: "BBD", name: "Barbadian dollar" },
  { value: "BDT", name: "Bangladeshi taka" },
  { value: "BGN", name: "Bulgarian lev" },
  { value: "BHD", name: "Bahraini dinar" },
  { value: "BIF", name: "Burundian franc" },
  { value: "BMD", name: "Bermudian dollar" },
  { value: "BND", name: "Brunei dollar" },
  { value: "BOB", name: "Boliviano" },
  { value: "BOV", name: "Bolivian Mvdol (funds code)" },
  { value: "BRL", name: "Brazilian real" },
  { value: "BSD", name: "Bahamian dollar" },
  { value: "BTN", name: "Bhutanese ngultrum" },
  { value: "BWP", name: "Botswana pula" },
  { value: "BYN", name: "Belarusian ruble" },
  { value: "BZD", name: "Belize dollar" },
  { value: "CAD", name: "Canadian dollar" },
  { value: "CDF", name: "Congolese franc" },
  { value: "CHF", name: "Swiss franc" },
  { value: "CLP", name: "Chilean peso" },
  { value: "CNY", name: "Chinese yuan" },
  { value: "COP", name: "Colombian peso" },
  { value: "CRC", name: "Costa Rican colón" },
  { value: "CUP", name: "Cuban peso" },
  { value: "CUC", name: "Cuban convertible peso" },
  { value: "CVE", name: "Cape Verdean escudo" },
  { value: "CZK", name: "Czech koruna" },
  { value: "DJF", name: "Djiboutian franc" },
  { value: "DKK", name: "Danish krone" },
  { value: "DOP", name: "Dominican peso" },
  { value: "DZD", name: "Algerian dinar" },
  { value: "EGP", name: "Egyptian pound" },
  { value: "ERN", name: "Eritrean nakfa" },
  { value: "ETB", name: "Ethiopian birr" },
  { value: "EUR", name: "Euro" },
  { value: "FJD", name: "Fiji dollar" },
  { value: "FKP", name: "Falkland Islands pound" },
  { value: "GBP", name: "Pound sterling" },
  { value: "GEL", name: "Georgian lari" },
  { value: "GHS", name: "Ghanaian cedi" },
  { value: "GIP", name: "Gibraltar pound" },
  { value: "GMD", name: "Gambian dalasi" },
  { value: "GNF", name: "Guinean franc" },
  { value: "GTQ", name: "Guatemalan quetzal" },
  { value: "GYD", name: "Guyanese dollar" },
  { value: "HKD", name: "Hong Kong dollar" },
  { value: "HNL", name: "Honduran lempira" },
  { value: "HRK", name: "Croatian kuna" },
  { value: "HTG", name: "Haitian gourde" },
  { value: "HUF", name: "Hungarian forint" },
  { value: "IDR", name: "Indonesian rupiah" },
  { value: "ILS", name: "Israeli new shekel" },
  { value: "INR", name: "Indian rupee" },
  { value: "IQD", name: "Iraqi dinar" },
  { value: "IRR", name: "Iranian rial" },
  { value: "ISK", name: "Icelandic króna" },
  { value: "JMD", name: "Jamaican dollar" },
  { value: "JOD", name: "Jordanian dinar" },
  { value: "JPY", name: "Japanese yen" },
  { value: "KES", name: "Kenyan shilling" },
  { value: "KGS", name: "Kyrgyzstani som" },
  { value: "KHR", name: "Cambodian riel" },
  { value: "KMF", name: "Comorian franc" },
  { value: "KPW", name: "North Korean won" },
  { value: "KRW", name: "South Korean won" },
  { value: "KWD", name: "Kuwaiti dinar" },
  { value: "KYD", name: "Cayman Islands dollar" },
  { value: "KZT", name: "Kazakhstani tenge" },
  { value: "LAK", name: "Lao kip" },
  { value: "LBP", name: "Lebanese pound" },
  { value: "LKR", name: "Sri Lankan rupee" },
  { value: "LRD", name: "Liberian dollar" },
  { value: "LSL", name: "Lesotho loti" },
  { value: "LYD", name: "Libyan dinar" },
  { value: "MAD", name: "Moroccan dirham" },
  { value: "MDL", name: "Moldovan leu" },
  { value: "MGA", name: "Malagasy ariary" },
  { value: "MKD", name: "North Macedonian denar" },
  { value: "MMK", name: "Myanma kyat" },
  { value: "MNT", name: "Mongolian tögrög" },
  { value: "MOP", name: "Macanese pataca" },
  { value: "MRU", name: "Mauritanian ouguiya" },
  { value: "MUR", name: "Mauritian rupee" },
  { value: "MVR", name: "Maldivian rufiyaa" },
  { value: "MWK", name: "Malawian kwacha" },
  { value: "MXN", name: "Mexican peso" },
  { value: "MXV", name: "Mexican investment unit (UDI)" },
  { value: "MYR", name: "Malaysian ringgit" },
  { value: "MZN", name: "Mozambican metical" },
  { value: "NAD", name: "Namibian dollar" },
  { value: "NGN", name: "Nigerian naira" },
  { value: "NIO", name: "Nicaraguan córdoba" },
  { value: "NOK", name: "Norwegian krone" },
  { value: "NPR", name: "Nepalese rupee" },
  { value: "NZD", name: "New Zealand dollar" },
  { value: "OMR", name: "Omani rial" },
  { value: "PAB", name: "Panamanian balboa" },
  { value: "PEN", name: "Peruvian sol" },
  { value: "PGK", name: "Papua New Guinean kina" },
  { value: "PHP", name: "Philippine peso" },
  { value: "PKR", name: "Pakistani rupee" },
  { value: "PLN", name: "Polish złoty" },
  { value: "PYG", name: "Paraguayan guaraní" },
  { value: "QAR", name: "Qatari riyal" },
  { value: "RON", name: "Romanian leu" },
  { value: "RSD", name: "Serbian dinar" },
  { value: "RUB", name: "Russian ruble" },
  { value: "RWF", name: "Rwandan franc" },
  { value: "SAR", name: "Saudi riyal" },
  { value: "SBD", name: "Solomon Islands dollar" },
  { value: "SCR", name: "Seychellois rupee" },
  { value: "SDG", name: "Sudanese pound" },
  { value: "SEK", name: "Swedish krona" },
  { value: "SGD", name: "Singapore dollar" },
  { value: "SHP", name: "Saint Helena pound" },
  { value: "SLL", name: "Sierra Leonean leone" },
  { value: "SOS", name: "Somali shilling" },
  { value: "SRD", name: "Surinamese dollar" },
  { value: "SSP", name: "South Sudanese pound" },
  { value: "STN", name: "São Tomé and Príncipe dobra (new)" },
  { value: "SVC", name: "Salvadoran colón" },
  { value: "SYP", name: "Syrian pound" },
  { value: "SZL", name: "Eswatini lilangeni" },
  { value: "THB", name: "Thai baht" },
  { value: "TJS", name: "Tajikistani somoni" },
  { value: "TMT", name: "Turkmenistan manat" },
  { value: "TND", name: "Tunisian dinar" },
  { value: "TOP", name: "Tongan paʻanga" },
  { value: "TRY", name: "Turkish lira" },
  { value: "TTD", name: "Trinidad and Tobago dollar" },
  { value: "TWD", name: "New Taiwan dollar" },
  { value: "TZS", name: "Tanzanian shilling" },
  { value: "UAH", name: "Ukrainian hryvnia" },
  { value: "UGX", name: "Ugandan shilling" },
  { value: "USD", name: "United States dollar" },
  { value: "USN", name: "US dollar (next day) (funds code)" },
  { value: "UYU", name: "Uruguayan peso" },
  {
    value: "UYI",
    name: "Uruguay Peso en Unidades Indexadas (UI) (funds code)",
  },
  { value: "UZS", name: "Uzbekistani soʻm" },
  { value: "VES", name: "Venezuelan bolívar soberano" },
  { value: "VED", name: "Venezuelan digital bolívar" },
  { value: "VND", name: "Vietnamese đồng" },
  { value: "VUV", name: "Vanuatu vatu" },
  { value: "WST", name: "Samoan tala" },
  { value: "XAF", name: "CFA franc BEAC" },
  { value: "XAG", name: "Silver (troy ounce) (funds code)" },
  { value: "XAU", name: "Gold (troy ounce) (funds code)" },
  { value: "XBA", name: "European Composite Unit (bond market unit)" },
  {
    value: "XBB",
    name: "European Monetary Unit (no longer used as currency code)",
  },
  { value: "XBC", name: "European Unit of Account (XBC)" },
  { value: "XBD", name: "European Unit of Account (XBD)" },
  { value: "XCD", name: "East Caribbean dollar" },
  { value: "XDR", name: "IMF Special Drawing Rights" },
  { value: "XOF", name: "CFA franc BCEAO" },
  { value: "XPD", name: "Palladium (troy ounce) (funds code)" },
  { value: "XPF", name: "CFP franc" },
  { value: "XPT", name: "Platinum (troy ounce) (funds code)" },
  { value: "XRE", name: "RINET Funds (funds code)" },
  { value: "XSU", name: "SUCRE (unit used by some regional organizations)" },
  { value: "XTS", name: "Testing code (reserved)" },
  { value: "XUA", name: "ADB Unit of Account" },
  {
    value: "XXX",
    name: "No currency (used for transactions without currency)",
  },
  { value: "YER", name: "Yemeni rial" },
  { value: "ZAR", name: "South African rand" },
  { value: "ZMW", name: "Zambian kwacha" },
  { value: "ZWL", name: "Zimbabwean dollar" },
];

const makeRecord = () =>
  Array.from({ length: 7 }, (_, i) => ({ value: String(i + 1), amount: 0 }));

export const initialAnalyticsChartValues = {
  totalRevenue: { record: makeRecord() },
  platformCommission: { record: makeRecord() },
  ownersPayouts: { record: makeRecord() },
  refundIssued: { record: makeRecord() },
};
